baseURL = "/"
title = "Hayybin"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
paginate = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[languages]
  [languages.en]
    languageName = "English"
    languageDirection = "ltr"
    weight = 1
    title = "Hayybin"
    [languages.en.params]
      description = "A blog about Technology, Lifestyle, Culture & Economics"

  [languages.ar]
    languageName = "العربية"
    languageDirection = "rtl"
    weight = 2
    title = "حيبن"
    [languages.ar.params]
      description = "مدونة عن التقنية وأسلوب الحياة والثقافة والاقتصاد"

[[languages.en.menus.main]]
  name = "Home"
  url = "/"
  weight = 1
[[languages.en.menus.main]]
  name = "Technology"
  url = "/categories/technology/"
  weight = 2
[[languages.en.menus.main]]
  name = "Lifestyle"
  url = "/categories/lifestyle/"
  weight = 3
[[languages.en.menus.main]]
  name = "Culture"
  url = "/categories/culture/"
  weight = 4
[[languages.en.menus.main]]
  name = "Economics"
  url = "/categories/economics/"
  weight = 5

[[languages.ar.menus.main]]
  name = "الرئيسية"
  url = "/"
  weight = 1
[[languages.ar.menus.main]]
  name = "التقنية"
  url = "/categories/technology/"
  weight = 2
[[languages.ar.menus.main]]
  name = "أسلوب الحياة"
  url = "/categories/lifestyle/"
  weight = 3
[[languages.ar.menus.main]]
  name = "الثقافة"
  url = "/categories/culture/"
  weight = 4
[[languages.ar.menus.main]]
  name = "الاقتصاد"
  url = "/categories/economics/"
  weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
